### PR TITLE
Added __array_wrap__ method to BoltArrayLocal

### PR DESCRIPTION
**Pull request by andrewosh**
If a `ufunc` is called on a `BoltArrayLocal`, it should never return an array with shape `()` (a single element). Standard `ndarray`s extract the scalar out of these arrays and return it instead. The `BoltArrayLocal.__array_wrap__` gives our local arrays the ability to extract out scalar values from ufunc results.

### CODE REVIEW

**Comment by freeman-lab** [comment]
Change looks great, maybe add a test or two to check this? Probably just in `test_local_basic`

**Comment by andrewosh** [comment]
K I actually added the tests to `test_local_functional` because I'm testing using the `sum` ufunc. Seemed good to keep that consistent with the spark version

**Comment by freeman-lab** [comment]
Cool, makes sense!

**Comment by freeman-lab** [comment]
LGTM, merging in.

**Pull request merged**
