### PR TITLE
Dask comparison in docs

### PR DESCRIPTION
**Pull request by freeman-lab**
This PR tries to expand and clarify comparisons to `dask`. It's a complex topic, but hopefully this helps (and provides the right links). It's also something we're trying to better quantify and understand on our own example workflows, and will add that soon, either in blog posts or docs.

Very open to suggestions / edits / improvements , esp @mrocklin @shoyer, thanks!

### CODE REVIEW

**Comment by mrocklin** [comment]
This all looks sane to me.  Sorry for the delay in response.

**Comment by mrocklin** [comment]
I would also be open to authoring a shared doc that was hosted on both sites.  Regardless I should write something on the dask docs.

**Comment by freeman-lab** [comment]
Thanks @mrocklin ! Will merge this in for now, but +1 to writing something together, really great idea. I can create a gdoc to get started.

**Comment by shoyer** [comment]
Agreed, this looks good. A joint document would work, but it isn't necessary -- h5py and pytables do a nice job in their FAQs of linking to the other project's answer to the same question.

**Comment by freeman-lab** [comment]
Cool thanks for taking a look @shoyer !

**Pull request merged**
